const fs = require('fs-extra');
const path = require('node:path');
const chalk = require('chalk');

/**
 * BME Module Installer
 * Standard module installer function that executes after IDE installations
 *
 * @param {Object} options - Installation options
 * @param {string} options.projectRoot - The root directory of the target project
 * @param {Object} options.config - Module configuration from install-config.yaml
 * @param {Array<string>} options.installedIDEs - Array of IDE codes that were installed
 * @param {Object} options.logger - Logger instance for output
 * @returns {Promise<boolean>} - Success status
 */
async function install(options) {
  const { projectRoot, config, logger } = options;

  try {
    logger.log(chalk.blue('🎓 Installing BME Developer Coaching Module...'));

    // Create learning output directory if configured
    if (config['learning_output_path']) {
      // Strip {project-root}/ prefix if present
      const learningPath = config['learning_output_path'].replace('{project-root}/', '');
      const learningDirPath = path.join(projectRoot, learningPath);

      if (await fs.pathExists(learningDirPath)) {
        logger.log(chalk.dim('Learning output directory already exists'));
      } else {
        logger.log(chalk.yellow(`Creating learning output directory: ${learningPath}`));
        await fs.ensureDir(learningDirPath);

        // Create a README to explain the directory
        const readmePath = path.join(learningDirPath, 'README.md');
        const readmeContent = `# Learning Journal

This directory contains your personalized learning plans, session notes, and progress tracking from BME Developer Coaching sessions.

## Contents

- **Learning Plans** - Structured roadmaps created by Morgan for skill development
- **Session Notes** - Records from coaching sessions and pair programming
- **Progress Tracking** - Your growth metrics and milestones

## Usage

Morgan automatically saves files here during coaching sessions. You can:
- Review past sessions to track your growth
- Reference learning plans when setting goals
- Share session notes with your team or mentors

---

🎓 Generated by BME Developer Coaching Module
`;
        await fs.writeFile(readmePath, readmeContent);
        logger.log(chalk.green('✓ Created learning output directory with README'));
      }
    }

    // Create Morgan's sidecar directories if they don't exist
    const bmadDir = path.join(projectRoot, config.bmad_folder || '.bmad');
    const morganSidecarPath = path.join(bmadDir, 'bme', 'agents', 'morgan-sidecar');

    // Ensure sessions directory exists
    const sessionsPath = path.join(morganSidecarPath, 'sessions');
    if (!(await fs.pathExists(sessionsPath))) {
      await fs.ensureDir(sessionsPath);
      logger.log(chalk.green('✓ Created Morgan session storage'));
    }

    // Ensure knowledge directory exists
    const knowledgePath = path.join(morganSidecarPath, 'knowledge');
    if (!(await fs.pathExists(knowledgePath))) {
      await fs.ensureDir(knowledgePath);
      logger.log(chalk.green('✓ Created Morgan knowledge base'));
    }

    logger.log(chalk.green('✨ BME Developer Coaching Module installed successfully!'));
    logger.log(chalk.dim('Load Morgan with: @morgan or agent morgan'));
    logger.log(chalk.dim('Start coaching with: *guided-story or *assess-level'));

    return true;
  } catch (error) {
    logger.error(chalk.red(`Failed to install BME module: ${error.message}`));
    return false;
  }
}

module.exports = { install };
